# Generated by Django 5.2.7 on 2025-11-01 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите название",
                        max_length=350,
                        unique=True,
                        verbose_name="Название",
                    ),
                ),
                (
                    "preview",
                    models.ImageField(
                        help_text="Прикрепите Ваше фото",
                        upload_to="materials/preview",
                        verbose_name="Фото",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Введите описание курса",
                        max_length=1000,
                        verbose_name="Описание",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите название",
                        max_length=350,
                        unique=True,
                        verbose_name="Название",
                    ),
                ),
                (
                    "preview",
                    models.ImageField(
                        help_text="Прикрепите фото",
                        upload_to="materials/preview",
                        verbose_name="Фото",
                    ),
                ),
                (
                    "link",
                    models.CharField(
                        help_text="Прикрепите ссылку на видео",
                        max_length=350,
                        unique=True,
                        verbose_name="Ссылка на видео",
                    ),
                ),
                (
                    "description",
                    models.ForeignKey(
                        blank=True,
                        help_text="Введите описание урока",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="materials.course",
                        verbose_name="Описание",
                    ),
                ),
            ],
            options={
                "verbose_name": "Курс",
                "verbose_name_plural": "Курсы",
            },
        ),
    ]
