# Generated by Django 5.2.7 on 2025-11-05 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0003_lesson_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.CharField(
                blank=True,
                help_text="Введите описание курса",
                max_length=1000,
                null=True,
                verbose_name="Описание",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="preview",
            field=models.ImageField(
                blank=True,
                help_text="Прикрепите Ваше фото",
                null=True,
                upload_to="materials/preview",
                verbose_name="Фото",
            ),
        ),
    ]
