# Generated by Django 5.2.7 on 2025-11-05 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0004_alter_course_description_alter_course_preview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Введите описание урока",
                null=True,
                verbose_name="Описание",
            ),
        ),
    ]
