# Generated by Django 5.2.7 on 2025-11-06 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0006_alter_course_options_alter_lesson_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="preview",
            field=models.ImageField(
                blank=True,
                help_text="Прикрепите фото",
                null=True,
                upload_to="materials/preview",
                verbose_name="Фото",
            ),
        ),
    ]
