# Generated by Django 5.2.7 on 2025-11-20 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0007_alter_lesson_preview"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="updated_at",
            field=models.TimeField(auto_now=True),
        ),
    ]
